version: 0.1.0   

name: A stack to deploy nextjs site to AWS S3
description: A stack to deploy nextjs site to AWS S3

branding:
  icon: 'aws.svg'
  color: 'blue'

inputs:

  - name: AWS_KEY_ID
    description: This will be used only once, we will discard it once we generate a OIDC token exchange
    required: true
    
  - name: AWS_SECRET_ACCESS_KEY
    description: This will be used only once, we will discard it once we generate a OIDC token exchange
    required: true

  - name: AWS_REGION
    description: Which Region do you want to Deploy to?
    is_secret: true
    required: true

  - name: AWS_S3_BUCKET_NAME
    description: Provide a Unique name for your AWS S3 Bucket
    is_secret: true
    required: true

  - name: AWS_ROLE_NAME
    description: Provide a Unique name for your AWS Role. We will create it for you and setup trust between Github and AWS
    is_secret: true
    required: true

  - name: USE_EXISTING_BUCKET
    description: Is this an existing S3 Bucket (Type true or false, Default value is false)?
    default: 'false'
    validvalues:                                       
    - 'true'
    - 'false'
    # type: boolean # TODO: Change it to boolean once we figure out how to get the string value into secrets

configs:
  - repo-metadata:
      parameters:
        description: 'NextJS + AWS'
        secrets: 
          - name: AWS_S3_BUCKET_NAME
            value: {{inputs.AWS_S3_BUCKET_NAME}}
          - name: AWS_REGION
            value: {{inputs.AWS_REGION}}
          - name: AWS_ROLE_NAME
            value: {{inputs.AWS_ROLE_NAME}}
        topics:
        - nextjs
        - aws

  - branches:   
    - name: main
      parameters:
        dismiss-stale-reviews: true                      
        required-approving-review-count: 0
        require-code-owner-reviews: false

  - environments:                                        
    - name: production
      parameters:
        protected-branches: true

github-apps:
- name: AWS

init:
- uses: ".github/workflows/stack-init.yaml"
